const productData = [
  {
    id: "health",
    product: "Health",
    data: [
      {
        id: "h-b1",
        category: "health",
        price: 100,
        name: "Benefit 1",
        qt: 1,
        selected: false,
        details: "details",
      },
      {
        id: "h-b2",
        category: "health",
        price: 200,
        name: "Benefit 2",
        qt: 2,
        selected: true,
        details: "details",
      },
      {
        id: "h-b3",
        category: "health",
        price: 300,
        name: "Benefit 3",
        qt: 3,
        selected: false,
        details: "details",
      },
      {
        id: "h-b4",
        category: "health",
        price: 400,
        name: "Benefit 4",
        qt: 4,
        selected: false,
        details: "details",
      },
    ],
  },
  {
    id: "life",
    product: "Life",
    data: [
      {
        id: "l-b1",
        category: "life",
        price: 300,
        name: "Benefit 1",
        qt: 0.5,
        selected: false,
        details: "details",
      },
      {
        id: "l-b2",
        category: "life",
        price: 400,
        name: "Benefit 2",
        qt: 1,
        selected: true,
        details: "details",
      },
      {
        id: "l-b3",
        category: "life",
        price: 450,
        name: "Benefit 3",
        qt: 2,
        selected: false,
        details: "details",
      },
      {
        id: "l-b4",
        category: "life",
        price: 600,
        name: "Benefit 4",
        qt: 1,
        selected: false,
        details: "details",
      },
    ],
  },
  {
    id: "accident",
    product: "Accident",
    data: [
      {
        id: "a-b1",
        category: "accident",
        price: 100,
        name: "Benefit 1",
        qt: 1,
        selected: false,
        details: "details",
      },
      {
        id: "a-b2",
        category: "accident",
        price: 250,
        name: "Benefit 2",
        qt: 1,
        selected: false,
        details: "details",
      },
      {
        id: "a-b3",
        category: "accident",
        price: 600,
        name: "Benefit 3",
        qt: 1,
        selected: true,
        details: "details",
      },
      {
        id: "a-b4",
        category: "accident",
        price: 750,
        name: "Benefit 4",
        qt: 1,
        selected: false,
        details: "details",
      },
    ],
  },
];
export default productData;
